### ISSUE TITLE
the relationship between sdn-wise-java and 01-GetStarted.jar

### ISSUE THREAD

**Issue by huangmg2017** [sdnwiselab/sdn-wise-java#10]
Hello, Milardo
I am very interesting in sdn-wise. Now I have read the code of sdn-wise-java and 01-GetStarted.jar, and I also change the number of motes successful when simulating with COOJA. As much as I know, the files of 01-GetStarted.jar ( controller ) almost in the sdn-wise-java/ctrl and the dependence sdn-wise-api comes from sdn-wise-java/core. By the way, the mote.java and sink.java is also in the sdn-wise-java/data. So my question is when I want to add another function( as data fuse ) to sdn-wise, what should I do? 
thank you very much.
Huangmg

**Comment by hieu1204** [comment]
I have the same question, hope to see your answer soon

**Comment by SebMilardo** [comment]
Hi,

sorry for the delayed response, but I was working on a different project. 
Anyway, to add a new functionality to the Java node you have to work in the sdn-wise-java/data folder. 
Then, If you want to use it inside Cooja you have to 

- compile sdn-wise-java: 

`cd /path/to/sdn-wise-contiki/sdn-wise-java && mvn clean install`

- copy the sdn-wise-data.jar file into the sdn-wise-contiki/sdn-wise-emulated/lib/ folder: 

`cd /path/to/sdn-wise-java/data/target/
  cp sdn-wise-data-X.X.X-jar-with-dependencies.jar /path/to/sdn-wise-contiki/sdn-wise-emulated/lib/sdn-wise-data.jar'

- and finally recompile the Cooja node:

`cd /path/to/sdn-wise-contiki/sdn-wise-emulated && ant jar`

**Comment by BasmaHegab** [comment]
hi .
I ran the code on netbeans 8 but it couldn't run. Also, I ran it on Ubuntu and I followed all your steps. it gives me an error
"Unable to build project '/home/user/sdn-wise-java/pom.xml; it requires Maven version 3.0.3"
and the existing maven is 3.5.0 . can you help me, please.

**Comment by SebMilardo** [comment]
Hi, please remove your version of Maven and install the required version

**Comment by BasmaHegab** [comment]
thanks for your response :)
I tried that solution but also did not work. finally, I tried eclipse and gave me the same result "
Missing artifact com.github.sdnwiselab:sdn-wise-data:jar:4.0.1-SNAPSHOT	pom.xml	/ctrl	line 28	Maven Dependency Problem"
I really need to run the code on a java compiler to add functions. If you recommend me a compiler to use I will be very grateful.
Thanks a lot.

**Comment by hieu1204** [comment]
I'm currently working on SDN- WISE with IntelliJ IDEA. It also support
Maven library so you don't need to import anything ( in Eclipse you have to
import Maven library )

**Comment by ftouch007** [comment]
hello please am having a problem when following the get started my cooja wont compile always bringing out error couldnt find symbols and error when i try to run
any help

**Comment by Winner2223** [comment]
Hi,
Firstly, thanks to Mr.SebMilardo for this contribution in the field. 
I am also trying to work on this area as I am a begginer and following Get Started with SDN-Wise, when i use java-alternative command it call for IceTeaPlugin which i have installed and the error is removed but while running the same alternative command it said 
--"update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-8-openjdk-i386/jre/lib/i386/IcedTeaPlugin.so"

As it does not throws any error so i continued but when i entered this command "ant compile"  it gives multiple errors one of them is org.contikios.cooja.* not exist? 
Why I am facing these errors?  am I doing some thing wrong?

Kindly guide in this regards.

**Comment by SebMilardo** [comment]
@ftouch007 Please open a new issue and write exactly what errors do you get

**Comment by SebMilardo** [comment]
@Winner2223 Please open a new issue and write down the steps necessary to reproduce the errors you get

**Comment by Winner2223** [comment]
SebMilardo Thank you for response issues are resolved.

**Comment by chellig** [comment]
bonjour , quelqu'un peut me aider pour cet probleme lors de l'installation 
''user@instant-contiki:~/cooja/examples/sdn-wise_java$ sudo update-java-alternatives -s java-1.8.0-openjdk-i386[sudo] password for user: 
update-alternatives: error: no alternatives for mozilla-javaplugin.so
update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-8-openjdk-i386/jre/lib/i386/IcedTeaPlugin.so''???????????

**Comment by SebMilardo** [comment]
Ciao! Ti consiglio intanto di scrivere in Inglese, magari aprendo un issue autonomo, in modo che la tua domanda possa essere d'aiuto anche ad altri. Hai provato a cercare su google? il primo risultato per il tuo errore è https://askubuntu.com/questions/141791/is-there-a-way-to-update-all-java-related-alternatives fammi sapere se sono stato d'aiuto

**Comment by Winner2223** [comment]
Hello , Milardo i hope so you are doing good. I am.working on SDN WISE and the given framework have only functionality of one hop data forwarding towards sink... I need to have multihop communication... Can you guide where from where I should start

**Comment by SebMilardo** [comment]
Hi, I will not repeat it again. 

1) Open a new issue. 
2) Describe your problem. 
3) Describe your system. Both hardware and software. 
4) Write me any error message you received. 
5) Tell me what you have done/tried to make it work.
6) If it is an error that is not related directly to sdn-wise search your exact error on https://duckduckgo.com/ and post in the issue a screenshot of it 
and Finally: 

**6) DO NOT COMMENT CLOSED ISSUE**
