### ISSUE TITLE
A lack of file "config.ini"

### ISSUE THREAD

**Issue by kopida** [sdnwiselab/sdn-wise-java#12]
Hi, I got the sdn-wise-java and built it with Eclipse. However, when I run it, there was an error with the lack of file "config.ini". Can you please help me with this file.

Thank you so much!

**Comment by SebMilardo** [comment]
The file is inside /ctrl/src/main/resources/. If you import the project in Intellij as Maven project it should work automatically

**Comment by kopida** [comment]
Thank you so much, SebMilardo. I can run it with Maven.
