### ISSUE TITLE
path of the folder named 'sdn-wise_java' does not exists and the file sdn-wise_java.tar.gz is not available

### ISSUE THREAD

**Issue by eyrebrasil** [sdnwiselab/sdn-wise-java#16]
Hi @SebMilardo ,

I have followed the instruction on the link: http://sdn-wise.dieei.unict.it/docs/guides/GetStarted.html to. But I can't run these commands below:
cd ~/contiki/tools
wget http://sdn-wise.dieei.unict.it/tools/sdn-wise_java.tar.gz
tar xvf sdn-wise_java.tar.gz
rm sdn-wise_java.tar.gz
cd cooja
git submodule update --init
ant jar_cooja
cd examples/sdn-wise_java
ant compile

the http://sdn-wise.dieei.unict.it/tools/sdn-wise_java.tar.gz is not available. I tried to use the project https://github.com/sdnwiselab/sdn-wise-java instead, but the folder cooja/examples/sdn-wise_java does not exists.

Could you please help me solve this problem?
thank you very much for your help

**Comment by SebMilardo** [comment]
The whole website (and all our backups) were hosted on some servers at the University of Catania. Unfortunately, most of the servers are actually under maintenance and we do not know when everything will be restored. I'll keep you updated.

**Comment by eyrebrasil** [comment]
Thank you for your time. Please, let me know of any update.

**Comment by SebMilardo** [comment]
The website is up! https://sdnwiselab.github.io
