### ISSUE TITLE
Building sdn-wise_java.targ.gz code and SDN-WISE network

### ISSUE THREAD

**Issue by kopida** [sdnwiselab/sdn-wise-java#3]
Hi, after looking at your code, I totally appreciate your contribution to the code. I really want to learn your work. 
Could you please guide me:
- how to build the file sdn-wise_java.tar.gz?
- what should be included in the file sdn-wise_java.tar.gz?
- how the user make request to the SDN-WISE network?
- where can we add input 
- where is the suitable location of the core modules when simulating SDN-WISE network with Cooja?

I appreciate if you could provide me with the guideline document about how to simulate the SDN-WISE network with Cooja.

Many thanks!

Regards,
Chau

**Comment by kopida** [comment]
Hi, I really appreciate your work on ONOS controller for SDN-WISE.

Could you please advice me whether it is possible to modify the java source codes for SDN-WISE components as the controller or simulated nodes?

Your SDN-WISE framework is very useful for researchers to test their design regarding SDN-WSN integration, but it would be great if you can instruct us how to modify or where to customize your framework to integrate new features into your framework.

I am looking forward to your responses.

Kind regards,
Chau

**Comment by huangmg2017** [comment]
I am also concerned about this issue.

**Comment by SebMilardo** [comment]
Hi,

We have updated the code and the readme files for our project so you can start by having a look at them. Then you can refer to #10 for details on how to work with the emulated node. Anyway we are going to add some more tutorial on the website so stay tuned.
