### ISSUE TITLE
How to write my frist application on top of ONOS in SDN-Wise???

### ISSUE THREAD

**Issue by engantar2007** [sdnwiselab/sdn-wise-java#4]
Dear All,
I am working on how to optimize energy consumption in IoT.  
Is there any basic tutorial on how to write an application on top of ONOS in SDN-Wise for node controlling such as switching off/on radio.
Thank you.

**Comment by SebMilardo** [comment]
Hi,

At the moment there are no controls implemented in ONOS to manage the physical layer of a mote. ONOS can only manage the routing of SDN-WISE nodes, but I'm planning to add some PHY related functionalities in the future. A tutorial on "how to write an app for ONOS and SDN-WISE" will be published soon on our website so stay tuned.
