### ISSUE TITLE
Controlling heterogeneous networks using SDN-WISE and ONOS

### ISSUE THREAD

**Issue by mohammad177** [sdnwiselab/sdn-wise-java#6]
Thank you for your article in: http://sdn-wise.dieei.unict.it/docs/guides/GetStartedONOS.html

But my problem is: 

In Step 3: Start!

I wrote: " source ~/.bashrc && source $ONOS_ROOT/tools/dev/bash_profile && karaf clean "
and ONOS started successfully, but when I typed " http://localhost:8181/onos/ui " in the browser, It showed me a blank page , not ONOS page.

This screenshot shows my problem:
http://s8.picofile.com/file/8271286142/Start_ONOS.jpg

please help me to solve the problem

thanks

**Comment by SebMilardo** [comment]
Hi,

I have updated the sdn-wise.sh script. Now It should be fine. Let me know if you have any issue
