### ISSUE TITLE
sdn-wise with onos

### ISSUE THREAD

**Issue by hlabi** [sdnwiselab/sdn-wise-java#7]
Good day Sebastiano

Does sdn-wise only work with onos version 1.0.0? i have been trying to run a cluster using different VMs through onos-form-cluster script but cannot seem to get it right. are there any settings that i need to consider? 

Thanks

**Comment by SebMilardo** [comment]
Hi,

Actually our solution supports only ONOS 1.0.2. I'm aware of problems with other versions of ONOS and I'm actually working to update this dependency. The next release of SDN-WISE will support  the latest version of ONOS

**Comment by hlabi** [comment]
Hi Sebastiano

Thank you very much for your swift response.

Last question: i am battling to get the working control cluster using sdnwise-onos (1.0.2-SNAPSHOT). I tried different methods as suggested on the ONOS documentations. one of those being the "onos-form-cluster" command. i installed sdnwise-onos in different VMs and i use this command to create a cluster, but i get an error. **Problem accessing /onos/v1/cluster/configuration**. The ONOS mailing list has this error addressed in the latest versions, however i'm not getting the resolve for this version.

is there anything i am missing with settings or is there another way to create a distributed control using sdnwise-onos?

Thank you very much.

**Comment by hlabi** [comment]
Hi Sebastiano

I finally managed to resolve this and created a cluster of controllers using cells as explained in this https://wiki.onosproject.org/display/ONOS/Environment+setup+with+cells 

Thanks
