### ISSUE TITLE
SDN-wise and ONOS controller???

### ISSUE THREAD

**Issue by mokli** [sdnwiselab/sdn-wise-java#8]
Hi Sebastiano,
I'm trying to perform your guides " Controlling heterogeneous networks using SDN-WISE and ONOS " but I have a problem.
first, I entered following code,
cd && wget http://sdn-wise.dieei.unict.it/tools/sdn-wise.sh && sudo chmod +rx sdn-wise.sh 
then I inserted
sudo ./sdn-wise.sh

afterward when I inserted the following commands

echo "export ONOS_ROOT=~/onos" >> ~/.bashrc && source ~/.bashrc && source $ONOS_ROOT/tools/dev/bash_profile && cd ~/onos && mvn clean install -DskipTests && cp ${ONOS_ROOT}/tools/package/branding/target/onos-branding-1.0.2-SNAPSHOT.jar ${KARAF_ROOT}/lib/

I met this error

The program 'mvn' can be found in the following packages:
 * maven
 * maven2
Try: sudo apt-get install <selected package>

How can I resolve it?

Thanks

**Comment by SebMilardo** [comment]
Hi,

The installation of maven is included in the sdn-wise.sh script so I guess something went wrong.
Try reinstall maven (run in a terminal: sudo apt-get install maven) and if you get any error let me know
