### ISSUE TITLE
Error when loading class from: Path_sdn-wise_java/build com.github.sdnwiselab.sdnwise.cooja.Sink

### ISSUE THREAD

**Issue by newdevos** [sdnwiselab/sdn-wise-java#9]
Dears,

I am very interested to your project sdn_wise.
Currently I am using your guide: http://sdn-wise.dieei.unict.it/docs/guides/GetStarted.html.
But I am facing a problem to import the new mote type: Sink.
In fact, I have got these error messages:
     [java] Caused by: java.lang.ClassNotFoundException: com.github.sdnwiselab.sdnwise.packet.NetworkPacket
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java] 	... 46 more
     [java] FATAL [AWT-EventQueue-0] (GUI.java:2172) - Exception when creating mote type
     [java] se.sics.cooja.MoteType$MoteTypeCreationException: Error when loading class from: /home/user/contiki/tools/cooja/examples/sdn-wise_java/build com.github.sdnwiselab.sdnwise.cooja.Sink
     [java] 	at se.sics.cooja.motes.ImportAppMoteType.createError(ImportAppMoteType.java:164)
     [java] 	at se.sics.cooja.motes.ImportAppMoteType.configureAndInit(ImportAppMoteType.java:154)
     [java] 	at se.sics.cooja.GUI.doCreateMoteType(GUI.java:2167)
     [java] 	at se.sics.cooja.GUI.doCreateMoteType(GUI.java:2146)
     [java] 	at se.sics.cooja.GUI$GUIEventHandler.actionPerformed(GUI.java:2928)
     [java] 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
     [java] 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
     [java] 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
     [java] 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
     [java] 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
     [java] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
     [java] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
     [java] 	at java.awt.Component.processMouseEvent(Component.java:6533)
     [java] 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
     [java] 	at java.awt.Component.processEvent(Component.java:6298)
     [java] 	at java.awt.Container.processEvent(Container.java:2236)
     [java] 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
     [java] 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
     [java] 	at java.awt.Component.dispatchEvent(Component.java:4711)
     [java] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
     [java] 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
     [java] 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
     [java] 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
     [java] 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
     [java] 	at java.awt.Component.dispatchEvent(Component.java:4711)
     [java] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
     [java] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
     [java] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
     [java] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
     [java] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
     [java] 	at java.awt.EventQueue$4.run(EventQueue.java:731)
     [java] 	at java.awt.EventQueue$4.run(EventQueue.java:729)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
     [java] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
     [java] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
     [java] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     [java] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
     [java] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [java] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
     [java] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
     [java] Caused by: java.lang.NoClassDefFoundError: com/github/sdnwiselab/sdnwise/packet/NetworkPacket
     [java] 	at java.lang.Class.getDeclaredConstructors0(Native Method)
     [java] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
     [java] 	at java.lang.Class.getConstructor0(Class.java:3075)
     [java] 	at java.lang.Class.getConstructor(Class.java:1825)
     [java] 	at se.sics.cooja.motes.ImportAppMoteType.configureAndInit(ImportAppMoteType.java:150)
     [java] 	... 41 more
     [java] Caused by: java.lang.ClassNotFoundException: com.github.sdnwiselab.sdnwise.packet.NetworkPacket
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Have you an idea how to fix it ?
I really appriciate your support.
Kind regards

**Comment by newdevos** [comment]
I fix this problem by using the last version (3) of Instant Contiki image.
Thanks for your good work.
Could you please tell us when the integration of ONOS and Cooja can be done ?

**Comment by SebMilardo** [comment]
Hi, you can find more details on ONOS and Cooja here https://github.com/sdnwiselab/onos
